title: "Anastasiya Lavrenchuk Portfolio"
email: anastasia.lavrenchuk@gmail.com
timezone: GMT
baseurl: '/portfolio'
permalink: "/:title/"
logo: 'assets/images/logo-transparent.png'
favicon: 'assets/images/favicon.ico'
author: Ana
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 5
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  ana:
    name: Ana
    display_name: Ana
    avatar: 'assets/images/ana.png'
    email: anastasia.lavrenchuk@gmail.com
    web: https://www.linkedin.com/in/anastasiya-lavrenchuk/

# Social
social:
  linkedin: https://www.linkedin.com/in/anastasiya-lavrenchuk/
  github: https://github.com/thislavrenchuk

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives